
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["host_postgres"] %>
  port: <%= ENV["port_postgres"] %>
  username: <%= ENV["username_postgres"] %>
  password: <%= ENV["password_postgres"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ApiRailsToken_development

test:
  <<: *default
  database: ApiRailsToken_test

production:
  <<: *default
  database: ApiRailsToken_production
  username: ApiRailsToken
  password: <%= ENV["APIRAILSTOKEN_DATABASE_PASSWORD"] %>
